- capsules:
  - id: 1
    lifecycle_environments:
    - id: 1
    - id: 2
    - id: 3
    - id: 4
    name: sat.ofam.dev
  content_views:
  - id: 9
    name: RHEL6_CV
  - id: 10
    name: AAP_24
  - id: 11
    name: RHEL9_AAP24_CCV
  - id: 19
    name: AAP_25
  - id: 20
    name: RHEL9_AAP25_CCV
  - id: 3
    name: RHEL7_CV
  - id: 13
    name: RHEL7_LEAPP_CCV
  - id: 15
    name: RHEL8_LEAPP_CCV
  - id: 12
    name: RHEL810_CV
  - id: 17
    name: RHEL96_CV
  - id: 18
    name: RHEL10_CV
  - id: 4
    name: RHEL9_CV
  - id: 2
    name: RHEL8_CV
  counts:
    content_hosts: 0
    content_views: 13
    deb_repositories: 0
    debs: 0
    docker_repositories: 0
    errata:
      bugfix: 17753
      enhancement: 2213
      security: 6164
      total: 26130
    module_streams: 1150
    ostree_repositories: 0
    packages: 194942
    products: 3
    yum_repositories: 21
  created_at: 2023-09-02 02:49:12 UTC
  description: null
  id: 1
  label: Library
  library: true
  name: Library
  organization:
    id: 1
    label: My_Organization
    name: My_Organization
  organization_id: 1
  permissions:
    create_lifecycle_environments: true
    destroy_lifecycle_environments: false
    edit_lifecycle_environments: true
    promote_or_remove_content_views_to_environments: true
    view_lifecycle_environments: true
  prior: null
  registry_name_pattern: null
  registry_unauthenticated_pull: false
  successor: null
  updated_at: 2023-09-02 02:49:12 UTC
- capsules:
  - id: 1
    lifecycle_environments:
    - id: 1
    - id: 2
    - id: 3
    - id: 4
    name: sat.ofam.dev
  content_views: []
  counts:
    content_hosts: 0
    content_views: 0
  created_at: 2023-09-02 03:41:30 UTC
  description: null
  id: 4
  label: PROD
  library: false
  name: PROD
  organization:
    id: 1
    label: My_Organization
    name: My_Organization
  organization_id: 1
  permissions:
    create_lifecycle_environments: true
    destroy_lifecycle_environments: true
    edit_lifecycle_environments: true
    promote_or_remove_content_views_to_environments: true
    view_lifecycle_environments: true
  prior:
    id: 3
    name: QA
  registry_name_pattern: null
  registry_unauthenticated_pull: false
  successor: null
  updated_at: 2023-09-02 03:41:30 UTC
- capsules:
  - id: 1
    lifecycle_environments:
    - id: 1
    - id: 2
    - id: 3
    - id: 4
    name: sat.ofam.dev
  content_views: []
  counts:
    content_hosts: 0
    content_views: 0
  created_at: 2023-09-02 03:41:19 UTC
  description: null
  id: 3
  label: QA
  library: false
  name: QA
  organization:
    id: 1
    label: My_Organization
    name: My_Organization
  organization_id: 1
  permissions:
    create_lifecycle_environments: true
    destroy_lifecycle_environments: true
    edit_lifecycle_environments: true
    promote_or_remove_content_views_to_environments: true
    view_lifecycle_environments: true
  prior:
    id: 2
    name: TEST
  registry_name_pattern: null
  registry_unauthenticated_pull: false
  successor:
    id: 4
    name: PROD
  updated_at: 2023-09-02 03:41:19 UTC
- capsules:
  - id: 1
    lifecycle_environments:
    - id: 1
    - id: 2
    - id: 3
    - id: 4
    name: sat.ofam.dev
  content_views:
  - id: 9
    name: RHEL6_CV
  - id: 12
    name: RHEL810_CV
  - id: 10
    name: AAP_24
  - id: 11
    name: RHEL9_AAP24_CCV
  - id: 19
    name: AAP_25
  - id: 20
    name: RHEL9_AAP25_CCV
  - id: 3
    name: RHEL7_CV
  - id: 13
    name: RHEL7_LEAPP_CCV
  - id: 15
    name: RHEL8_LEAPP_CCV
  - id: 17
    name: RHEL96_CV
  - id: 18
    name: RHEL10_CV
  - id: 4
    name: RHEL9_CV
  - id: 2
    name: RHEL8_CV
  counts:
    content_hosts: 7
    content_views: 13
  created_at: 2023-09-02 03:40:43 UTC
  description: null
  id: 2
  label: TEST
  library: false
  name: TEST
  organization:
    id: 1
    label: My_Organization
    name: My_Organization
  organization_id: 1
  permissions:
    create_lifecycle_environments: true
    destroy_lifecycle_environments: false
    edit_lifecycle_environments: true
    promote_or_remove_content_views_to_environments: true
    view_lifecycle_environments: true
  prior:
    id: 1
    name: Library
  registry_name_pattern: null
  registry_unauthenticated_pull: false
  successor:
    id: 3
    name: QA
  updated_at: 2023-09-02 03:40:43 UTC
